name: Docker CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate version
        run: echo "VERSION=v1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          cd 02-docker/app
          docker build \
            -t mayalinux/cloud-native-app:${VERSION} \
            -t mayalinux/cloud-native-app:latest .

      - name: Run container test
        run: |
          docker run -d -p 5000:5000 --name test-app \
            mayalinux/cloud-native-app:${VERSION}
          sleep 5

      - name: Health check
        run: |
          curl --fail http://localhost:5000/health

      - name: Push to Docker Hub
        run: |
          docker push mayalinux/cloud-native-app:${VERSION}
          docker push mayalinux/cloud-native-app:latest

  deploy:
    needs: build-test-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/devops.pem
          chmod 600 ~/.ssh/devops.pem

      - name: Deploy with Ansible
        run: |
          ansible-playbook \
            -i "${{ secrets.EC2_HOST }}," \
            05-ansible/flask-deploy/playbook.yml \
            -u ${{ secrets.EC2_USER }} \
            --private-key ~/.ssh/devops.pem
